services:
  db:
    image: postgres:15-alpine
    container_name: share-it
    environment:
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
      POSTGRES_DB: shareit
    ports:
      - "6541:5432"
    healthcheck:
      test: pg_isready -q -d shareit -U shareit
      timeout: 5s
      interval: 5s
      retries: 10
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - SHAREIT_SERVER_URL=http://server:9090/api

volumes:
  postgres_data: