services:
  postgres:
    image: postgres:15-alpine
    container_name: later-pg
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: later
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: